import type {
  Finding,
  ScanReport,
  Severity
} from "../../core/findings/index.js";
import type { Reporter } from "../index.js";

const SEVERITY_ORDER: Severity[] = ["critical", "warning", "info"];

export const htmlReporter: Reporter = {
  format: "html",
  render(report) {
    return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ArcReady Report - ${escapeHtml(report.project)}</title>
  <style>
    :root {
      color-scheme: light;
      --bg: #f8fafc;
      --panel: #ffffff;
      --text: #0f172a;
      --muted: #475569;
      --border: #dbe3ef;
      --critical: #991b1b;
      --warning: #92400e;
      --info: #1d4ed8;
    }
    * { box-sizing: border-box; }
    body {
      margin: 0;
      background: var(--bg);
      color: var(--text);
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      line-height: 1.5;
    }
    .container {
      max-width: 960px;
      margin: 0 auto;
      padding: 32px 20px;
    }
    header, .card, .finding {
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 16px;
      box-shadow: 0 1px 2px rgba(15, 23, 42, 0.04);
    }
    header {
      padding: 28px;
      margin-bottom: 20px;
    }
    h1, h2, h3, p { margin-top: 0; }
    h1 { margin-bottom: 8px; font-size: 2rem; }
    h2 { margin: 28px 0 12px; }
    h3 { margin-bottom: 8px; }
    .meta {
      color: var(--muted);
      margin-bottom: 0;
    }
    .overview, .summary {
      display: grid;
      gap: 12px;
      grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
      margin-bottom: 20px;
    }
    .card {
      padding: 18px;
    }
    .label {
      color: var(--muted);
      display: block;
      font-size: 0.875rem;
      margin-bottom: 4px;
    }
    .value {
      font-size: 1.5rem;
      font-weight: 700;
    }
    .status, .severity {
      display: inline-block;
      border: 1px solid var(--border);
      border-radius: 999px;
      font-size: 0.875rem;
      font-weight: 700;
      padding: 2px 10px;
      text-transform: lowercase;
    }
    .severity-critical { color: var(--critical); }
    .severity-warning { color: var(--warning); }
    .severity-info { color: var(--info); }
    .finding {
      padding: 18px;
      margin-bottom: 12px;
    }
    .finding-meta {
      color: var(--muted);
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      margin-bottom: 12px;
    }
    code {
      background: #eef2f7;
      border-radius: 6px;
      padding: 2px 6px;
    }
    ul {
      margin: 8px 0 0;
      padding-left: 22px;
    }
    .docs {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      padding-left: 0;
      list-style: none;
    }
    .pill {
      background: #eef2ff;
      border: 1px solid #c7d2fe;
      border-radius: 999px;
      padding: 2px 10px;
    }
    footer {
      color: var(--muted);
      margin-top: 32px;
      text-align: center;
    }
  </style>
</head>
<body>
  <main class="container">
    <header>
      <h1>ArcReady Report</h1>
      <p class="meta">Project: ${escapeHtml(report.project)}</p>
    </header>

    <section class="overview" aria-label="Report overview">
      <div class="card"><span class="label">Score</span><span class="value">${report.score}</span></div>
      <div class="card"><span class="label">Status</span><span class="status">${escapeHtml(report.status)}</span></div>
    </section>

    <section aria-label="Summary">
      <h2>Summary</h2>
      <div class="summary">
        <div class="card"><span class="label">Critical</span><span class="value severity-critical">${report.summary.critical}</span></div>
        <div class="card"><span class="label">Warning</span><span class="value severity-warning">${report.summary.warning}</span></div>
        <div class="card"><span class="label">Info</span><span class="value severity-info">${report.summary.info}</span></div>
      </div>
    </section>

    ${renderFindings(report)}

    <footer>Generated by ArcReady</footer>
  </main>
</body>
</html>
`;
  }
};

function renderFindings(report: ScanReport): string {
  if (report.findings.length === 0) {
    return `<section aria-label="Findings">
      <h2>Findings</h2>
      <div class="card">No findings.</div>
    </section>`;
  }

  return SEVERITY_ORDER.map((severity) => {
    const findings = report.findings
      .filter((finding) => finding.severity === severity)
      .sort(compareFindings);

    if (findings.length === 0) {
      return "";
    }

    return `<section aria-label="${titleCase(severity)} findings">
      <h2>${titleCase(severity)} Findings</h2>
      ${findings.map(renderFinding).join("\n      ")}
    </section>`;
  })
    .filter(Boolean)
    .join("\n\n    ");
}

function renderFinding(finding: Finding): string {
  const files = [...finding.files].sort();
  const docs = finding.docs ? [finding.docs].sort() : [];

  return `<article class="finding">
        <h3>${escapeHtml(finding.ruleId)}</h3>
        <div class="finding-meta">
          <span>Preset: ${escapeHtml(finding.preset ?? "unknown")}</span>
          <span class="severity severity-${finding.severity}">Severity: ${escapeHtml(finding.severity)}</span>
        </div>
        <p><strong>Message:</strong> ${escapeHtml(finding.message)}</p>
        <div><strong>Files:</strong>${renderFiles(files)}</div>
        ${finding.suggestedFix ? `<p><strong>Suggested fix:</strong> ${escapeHtml(finding.suggestedFix)}</p>` : ""}
        ${docs.length > 0 ? `<div><strong>Docs:</strong>${renderDocs(docs)}</div>` : ""}
      </article>`;
}

function renderFiles(files: string[]): string {
  if (files.length === 0) {
    return "<ul><li><code>n/a</code></li></ul>";
  }

  return `<ul>${files.map((file) => `<li><code>${escapeHtml(file)}</code></li>`).join("")}</ul>`;
}

function renderDocs(docs: string[]): string {
  return `<ul class="docs">${docs.map((doc) => `<li class="pill">${escapeHtml(doc)}</li>`).join("")}</ul>`;
}

function compareFindings(left: Finding, right: Finding): number {
  return (
    left.severity.localeCompare(right.severity) ||
    left.ruleId.localeCompare(right.ruleId) ||
    left.message.localeCompare(right.message)
  );
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function titleCase(value: string): string {
  return `${value.slice(0, 1).toUpperCase()}${value.slice(1)}`;
}
