import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { createStubReport, runCli } from "../src/index.js";
import type { CliIo } from "../src/index.js";

const tempDirs: string[] = [];

afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    rmSync(dir, { recursive: true, force: true });
  }
});

describe("arcready CLI", () => {
  it("boots and prints help", async () => {
    const output: string[] = [];
    const code = await runCli(["--help"], createIo(output));

    expect(code).toBe(0);
    expect(output.join("")).toContain("arcready scan");
  });

  it("scan --format json returns a report object", async () => {
    const output: string[] = [];
    const io = createIo(output);
    const code = await runCli(["scan", "--format", "json"], io);
    const report = JSON.parse(output.join(""));

    expect(code).toBe(0);
    expect(report).toEqual(await createStubReport(io.cwd));
  });

  it("scan --format terminal prints readable output", async () => {
    const output: string[] = [];
    const io = createIo(output);

    const code = await runCli(["scan", "--format", "terminal"], io);
    const rendered = output.join("");

    expect(code).toBe(0);
    expect(rendered).toContain("ArcReady v");
    expect(rendered).toContain("Project:");
    expect(rendered).toContain("Score: 100");
    expect(rendered).toContain("No findings.");
  });

  it("scan defaults to terminal output", async () => {
    const output: string[] = [];
    const io = createIo(output);

    const code = await runCli(["scan"], io);

    expect(code).toBe(0);
    expect(output.join("")).toContain("No findings.");
  });

  it("scan uses package name when available", async () => {
    const output: string[] = [];
    const io = createIo(output);
    writeFileSync(join(io.cwd, "package.json"), '{"name":"fixture-app"}\n');

    const code = await runCli(["scan", "--format", "json"], io);
    const report = JSON.parse(output.join(""));

    expect(code).toBe(0);
    expect(report).toMatchObject({
      project: "fixture-app",
      score: 100,
      status: "pass",
      summary: {
        critical: 0,
        warning: 0,
        info: 0
      },
      findings: []
    });
  });

  it("scan --format json --out writes a JSON report", async () => {
    const output: string[] = [];
    const io = createIo(output);
    const outPath = join("reports", "arcready.json");

    const code = await runCli(
      ["scan", "--format", "json", "--out", outPath],
      io
    );
    const absoluteOutPath = join(io.cwd, outPath);
    const report = JSON.parse(readFileSync(absoluteOutPath, "utf8"));

    expect(code).toBe(0);
    expect(output.join("")).toBe("");
    expect(existsSync(absoluteOutPath)).toBe(true);
    expect(report).toEqual(await createStubReport(io.cwd));
  });

  it("scan --format markdown prints Markdown", async () => {
    const output: string[] = [];
    const io = createIo(output);

    const code = await runCli(["scan", "--format", "markdown"], io);
    const rendered = output.join("");

    expect(code).toBe(0);
    expect(rendered).toContain("# ArcReady Report");
    expect(rendered).toContain("## Summary");
    expect(rendered).toContain("No findings.");
  });

  it("scan --format markdown --out writes a Markdown report", async () => {
    const output: string[] = [];
    const io = createIo(output);
    const outPath = join("reports", "arcready.md");

    const code = await runCli(
      ["scan", "--format", "markdown", "--out", outPath],
      io
    );
    const absoluteOutPath = join(io.cwd, outPath);
    const rendered = readFileSync(absoluteOutPath, "utf8");

    expect(code).toBe(0);
    expect(output.join("")).toBe("");
    expect(existsSync(absoluteOutPath)).toBe(true);
    expect(rendered).toContain("# ArcReady Report");
  });

  it("scan --format html prints HTML", async () => {
    const output: string[] = [];
    const io = createIo(output);

    const code = await runCli(["scan", "--format", "html"], io);
    const rendered = output.join("");

    expect(code).toBe(0);
    expect(rendered).toContain("<!doctype html>");
    expect(rendered).toContain("<h1>ArcReady Report</h1>");
    expect(rendered).toContain("Generated by ArcReady");
  });

  it("scan --format html --out writes an HTML report", async () => {
    const output: string[] = [];
    const io = createIo(output);
    const outPath = join("reports", "arcready.html");

    const code = await runCli(
      ["scan", "--format", "html", "--out", outPath],
      io
    );
    const absoluteOutPath = join(io.cwd, outPath);
    const rendered = readFileSync(absoluteOutPath, "utf8");

    expect(code).toBe(0);
    expect(output.join("")).toBe("");
    expect(existsSync(absoluteOutPath)).toBe(true);
    expect(rendered).toContain("<!doctype html>");
  });
});

describe("arcready CLI scan exit codes", () => {
  it("clean scan exits 0", async () => {
    const code = await runCli(["scan"], createIo([]));
    expect(code).toBe(0);
  });

  it("critical finding exits 1 when failOn is critical (default)", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "critical" });
    const code = await runCli(["scan"], io);
    expect(code).toBe(1);
  });

  it("warning finding exits 0 when failOn is critical", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "warning", failOn: "critical" });
    const code = await runCli(["scan"], io);
    expect(code).toBe(0);
  });

  it("warning finding exits 1 when failOn is warning", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "warning", failOn: "warning" });
    const code = await runCli(["scan"], io);
    expect(code).toBe(1);
  });

  it("info finding exits 1 when failOn is info", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "info", failOn: "info" });
    const code = await runCli(["scan"], io);
    expect(code).toBe(1);
  });

  it("critical finding exits 0 when failOn is none", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "critical", failOn: "none" });
    const code = await runCli(["scan"], io);
    expect(code).toBe(0);
  });

  it("--fail-on none overrides config failOn critical", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "critical", failOn: "critical" });
    const code = await runCli(["scan", "--fail-on", "none"], io);
    expect(code).toBe(0);
  });

  it("--fail-on warning overrides config failOn none", async () => {
    const io = createIo([]);
    writeFindingFixture(io.cwd, { severity: "warning", failOn: "none" });
    const code = await runCli(["scan", "--fail-on", "warning"], io);
    expect(code).toBe(1);
  });
});

describe("arcready CLI scan error handling", () => {
  it("invalid config exits 2 with clean error message", async () => {
    const stdout: string[] = [];
    const stderr: string[] = [];
    const io = createIoWithStreams(stdout, stderr);
    writeFileSync(join(io.cwd, "arcready.config.json"), "not valid json");

    const code = await runCli(["scan"], io);

    expect(code).toBe(2);
    expect(stderr.join("")).toContain("ArcReady error:");
    expect(stdout.join("")).toBe("");
  });

  it("invalid config does not print raw stack trace", async () => {
    const stdout: string[] = [];
    const stderr: string[] = [];
    const io = createIoWithStreams(stdout, stderr);
    writeFileSync(join(io.cwd, "arcready.config.json"), "not valid json");

    await runCli(["scan"], io);

    // Stack trace lines start with whitespace + "at " (e.g. "    at Object.fn")
    expect(stderr.join("")).not.toMatch(/\n\s+at /);
  });

  it("unknown config key exits 2 with clear message", async () => {
    const stderr: string[] = [];
    const io = createIoWithStreams([], stderr);
    writeFileSync(
      join(io.cwd, "arcready.config.json"),
      JSON.stringify({ pressets: ["wallet"] })
    );

    const code = await runCli(["scan"], io);

    expect(code).toBe(2);
    expect(stderr.join("")).toContain("pressets");
  });
});

function createIo(output: string[]): CliIo {
  const cwd = mkdtempSync(join(tmpdir(), "arcready-"));
  tempDirs.push(cwd);

  return {
    cwd,
    stdout: {
      write: (chunk: string | Uint8Array) => {
        output.push(String(chunk));
        return true;
      }
    },
    stderr: {
      write: (chunk: string | Uint8Array) => {
        output.push(String(chunk));
        return true;
      }
    }
  };
}

function createIoWithStreams(
  stdout: string[],
  stderr: string[]
): CliIo {
  const cwd = mkdtempSync(join(tmpdir(), "arcready-"));
  tempDirs.push(cwd);

  return {
    cwd,
    stdout: {
      write: (chunk: string | Uint8Array) => {
        stdout.push(String(chunk));
        return true;
      }
    },
    stderr: {
      write: (chunk: string | Uint8Array) => {
        stderr.push(String(chunk));
        return true;
      }
    }
  };
}

interface FindingFixtureOptions {
  severity: "critical" | "warning" | "info";
  failOn?: "critical" | "warning" | "info" | "none";
}

function writeFindingFixture(
  cwd: string,
  options: FindingFixtureOptions
): void {
  const ruleId = "wallet/ONE_CONFIRMATION_FINAL";
  const config: Record<string, unknown> = {
    presets: ["wallet"],
    rules: { [ruleId]: options.severity }
  };

  if (options.failOn !== undefined) {
    config.failOn = options.failOn;
  }

  writeFileSync(
    join(cwd, "arcready.config.json"),
    JSON.stringify(config, null, 2)
  );

  mkdirSync(join(cwd, "src"), { recursive: true });
  writeFileSync(
    join(cwd, "src", "wallet.ts"),
    "const arcTestnet = { confirmations: 3 };\n"
  );
}
